//! Static data for the 40 Gokyo no Waza techniques.
//!
//! `slug` matches the judo.how URL pattern. `name_fr` and `name_en` are the
//! conventional literal translations (FFJDA/Kodokan style). `image_url` is
//! optional — when empty, the frontend tries
//! `src/assets/illustrations/<slug>.{gif,webp,png,jpg}` first, then falls
//! back to a category silhouette SVG. `youtube_id` is the judo.how reference
//! video ID on YouTube; empty string means judo.how does not yet host a
//! video for this technique.

use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct Technique {
    pub slug: &'static str,
    pub name: &'static str,        // romaji (international name)
    pub kanji: &'static str,
    pub name_fr: &'static str,     // French literal translation
    pub name_en: &'static str,     // English literal translation
    pub group: u8,
    pub category: &'static str,
    pub judo_how_url: &'static str,
    pub wikipedia_url: &'static str,
    pub image_url: &'static str,
    pub youtube_id: &'static str,
}

pub const TECHNIQUES: &[Technique] = &[
    // ----- Dai Ikkyō (1st group) -----
    Technique { slug: "de-ashi-harai",         name: "De-ashi-harai",         kanji: "出足払",   name_fr: "Balayage du pied avancé",                  name_en: "Forward foot sweep",                       group: 1, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/de-ashi-harai/",          wikipedia_url: "https://en.wikipedia.org/wiki/De_ashi_barai",          image_url: "", youtube_id: "4BUUvqxi_Kk" },
    Technique { slug: "hiza-guruma",            name: "Hiza-guruma",            kanji: "膝車",     name_fr: "Roue autour du genou",                     name_en: "Knee wheel",                                group: 1, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/hiza-guruma/",            wikipedia_url: "https://en.wikipedia.org/wiki/Hiza_guruma",            image_url: "", youtube_id: "JPJx9-oAVns" },
    Technique { slug: "sasae-tsurikomi-ashi",   name: "Sasae-tsurikomi-ashi",   kanji: "支釣込足", name_fr: "Blocage du pied par tirer-soulever",       name_en: "Propping drawing ankle throw",              group: 1, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/sasae-tsurikomi-ashi/",   wikipedia_url: "https://en.wikipedia.org/wiki/Sasae_tsurikomi_ashi",   image_url: "", youtube_id: "699i--pvYmE" },
    Technique { slug: "uki-goshi",              name: "Uki-goshi",              kanji: "浮腰",     name_fr: "Hanche flottante",                         name_en: "Floating hip throw",                        group: 1, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/uki-goshi/",             wikipedia_url: "https://en.wikipedia.org/wiki/Uki_goshi",              image_url: "", youtube_id: "bPKwtB4lyOQ" },
    Technique { slug: "o-soto-gari",            name: "O-soto-gari",            kanji: "大外刈",   name_fr: "Grand fauchage extérieur",                 name_en: "Major outer reaping",                       group: 1, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/o-soto-gari/",            wikipedia_url: "https://fr.wikipedia.org/wiki/O-soto-gari",            image_url: "", youtube_id: "c-A_nP7mKAc" },
    Technique { slug: "o-goshi",                name: "O-goshi",                kanji: "大腰",     name_fr: "Grande hanche",                            name_en: "Major hip throw",                           group: 1, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/o-goshi/",               wikipedia_url: "https://fr.wikipedia.org/wiki/O-Goshi",                image_url: "", youtube_id: "yhu1mfy2vJ4" },
    Technique { slug: "o-uchi-gari",            name: "O-uchi-gari",            kanji: "大内刈",   name_fr: "Grand fauchage intérieur",                 name_en: "Major inner reaping",                       group: 1, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/o-uchi-gari/",            wikipedia_url: "https://fr.wikipedia.org/wiki/%C5%8C-uchi-gari",       image_url: "", youtube_id: "0itJFhV9pDQ" },
    Technique { slug: "seoi-nage",              name: "Seoi-nage",              kanji: "背負投",   name_fr: "Projection par l'épaule (chargée)",        name_en: "Shoulder throw",                            group: 1, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/seoi-nage/",                wikipedia_url: "https://fr.wikipedia.org/wiki/Ippon-seoi-nage",        image_url: "", youtube_id: "zIq0xI0ogxk" },

    // ----- Dai Nikyō (2nd group) -----
    Technique { slug: "ko-soto-gari",           name: "Ko-soto-gari",           kanji: "小外刈",   name_fr: "Petit fauchage extérieur",                 name_en: "Minor outer reaping",                       group: 2, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/ko-soto-gari/",           wikipedia_url: "https://en.wikipedia.org/wiki/Ko_soto_gari",           image_url: "", youtube_id: "jeQ541ScLB4" },
    Technique { slug: "ko-uchi-gari",           name: "Ko-uchi-gari",           kanji: "小内刈",   name_fr: "Petit fauchage intérieur",                 name_en: "Minor inner reaping",                       group: 2, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/ko-uchi-gari/",           wikipedia_url: "https://fr.wikipedia.org/wiki/Ko-uchi-gari",           image_url: "", youtube_id: "3Jb3tZvr9Ng" },
    Technique { slug: "koshi-guruma",           name: "Koshi-guruma",           kanji: "腰車",     name_fr: "Roue autour de la hanche",                 name_en: "Hip wheel",                                 group: 2, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/koshi-guruma/",          wikipedia_url: "https://en.wikipedia.org/wiki/Koshi_guruma",           image_url: "", youtube_id: "SU7Id6uVJ44" },
    Technique { slug: "tsurikomi-goshi",        name: "Tsurikomi-goshi",        kanji: "釣込腰",   name_fr: "Hanche par tirer-soulever",                name_en: "Lifting-pulling hip throw",                 group: 2, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/tsurikomi-goshi/",       wikipedia_url: "https://en.wikipedia.org/wiki/Tsurikomi_goshi",        image_url: "", youtube_id: "McfzA0yRVt4" },
    Technique { slug: "okuri-ashi-harai",       name: "Okuri-ashi-harai",       kanji: "送足払",   name_fr: "Balayage des deux pieds (poursuivi)",      name_en: "Sliding-foot sweep",                        group: 2, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/okuri-ashi-harai/",       wikipedia_url: "https://en.wikipedia.org/wiki/Okuri_ashi_barai",       image_url: "", youtube_id: "nw1ZdRjrdRI" },
    Technique { slug: "tai-otoshi",             name: "Tai-otoshi",             kanji: "体落",     name_fr: "Renversement du corps",                    name_en: "Body drop",                                 group: 2, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/tai-otoshi/",               wikipedia_url: "https://en.wikipedia.org/wiki/Tai_otoshi",             image_url: "", youtube_id: "4x6S3Q-Ktv8" },
    Technique { slug: "harai-goshi",            name: "Harai-goshi",            kanji: "払腰",     name_fr: "Hanche balayée",                           name_en: "Sweeping hip throw",                        group: 2, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/harai-goshi/",           wikipedia_url: "https://fr.wikipedia.org/wiki/Harai-goshi",            image_url: "", youtube_id: "qTo8HlAAkOo" },
    Technique { slug: "uchi-mata",              name: "Uchi-mata",              kanji: "内股",     name_fr: "Fauchage intérieur de la cuisse",          name_en: "Inner-thigh throw",                         group: 2, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/uchi-mata/",              wikipedia_url: "https://fr.wikipedia.org/wiki/Uchi-mata",              image_url: "", youtube_id: "iUpSu5J-bgw" },

    // ----- Dai Sankyō (3rd group) -----
    Technique { slug: "ko-soto-gake",           name: "Ko-soto-gake",           kanji: "小外掛",   name_fr: "Petit accrochage extérieur",               name_en: "Minor outer hook",                          group: 3, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/ko-soto-gake/",           wikipedia_url: "https://fr.wikipedia.org/wiki/Ko-soto-gake",           image_url: "", youtube_id: "8b6kY4s4zH4" },
    Technique { slug: "tsuri-goshi",            name: "Tsuri-goshi",            kanji: "釣腰",     name_fr: "Hanche soulevée",                          name_en: "Lifting hip throw",                         group: 3, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/tsuri-goshi/",           wikipedia_url: "https://en.wikipedia.org/wiki/Tsuri_goshi",            image_url: "", youtube_id: "51Htlp7xEvE" },
    Technique { slug: "yoko-otoshi",            name: "Yoko-otoshi",            kanji: "横落",     name_fr: "Renversement de côté",                     name_en: "Side drop",                                 group: 3, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/yoko-otoshi/",    wikipedia_url: "https://en.wikipedia.org/wiki/Yoko_otoshi",            image_url: "", youtube_id: "MnNG67pF_a0" },
    Technique { slug: "ashi-guruma",            name: "Ashi-guruma",            kanji: "足車",     name_fr: "Roue par la jambe",                        name_en: "Leg wheel",                                 group: 3, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/ashi-guruma/",            wikipedia_url: "https://en.wikipedia.org/wiki/Ashi_guruma",            image_url: "", youtube_id: "ROeayhvom9U" },
    Technique { slug: "hane-goshi",             name: "Hane-goshi",             kanji: "跳腰",     name_fr: "Hanche bondissante",                       name_en: "Spring hip throw",                          group: 3, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/hane-goshi/",            wikipedia_url: "https://en.wikipedia.org/wiki/Hane_goshi",             image_url: "", youtube_id: "M9_7De6A1kk" },
    Technique { slug: "harai-tsurikomi-ashi",   name: "Harai-tsurikomi-ashi",   kanji: "払釣込足", name_fr: "Pied balayé par tirer-soulever",           name_en: "Lifting-pulling foot sweep",                group: 3, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/harai-tsurikomi-ashi/",   wikipedia_url: "https://en.wikipedia.org/wiki/Harai_tsurikomi_ashi",   image_url: "", youtube_id: "gGPXvWL8VbE" },
    Technique { slug: "tomoe-nage",             name: "Tomoe-nage",             kanji: "巴投",     name_fr: "Projection en cercle",                     name_en: "Circle throw",                              group: 3, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/ma-sutemi-waza/tomoe-nage/",       wikipedia_url: "https://fr.wikipedia.org/wiki/Tomoe-nage",             image_url: "", youtube_id: "880WbHvHv6A" },
    Technique { slug: "kata-guruma",            name: "Kata-guruma",            kanji: "肩車",     name_fr: "Roue autour des épaules",                  name_en: "Shoulder wheel",                            group: 3, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/kata-guruma/",              wikipedia_url: "https://en.wikipedia.org/wiki/Kata_guruma",            image_url: "", youtube_id: "cnHRhSy8yi4" },

    // ----- Dai Yonkyō (4th group) -----
    Technique { slug: "sumi-gaeshi",            name: "Sumi-gaeshi",            kanji: "隅返",     name_fr: "Renversement dans l'angle",                name_en: "Corner throw",                              group: 4, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/ma-sutemi-waza/sumi-gaeshi/",      wikipedia_url: "https://fr.wikipedia.org/wiki/Sumi-gaeshi",            image_url: "", youtube_id: "5VhduA5xkbA" },
    Technique { slug: "tani-otoshi",            name: "Tani-otoshi",            kanji: "谷落",     name_fr: "Renversement dans la vallée",              name_en: "Valley drop",                               group: 4, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/tani-otoshi/",    wikipedia_url: "https://en.wikipedia.org/wiki/Tani_otoshi",            image_url: "", youtube_id: "3b9Me3Fohpk" },
    Technique { slug: "hane-makikomi",          name: "Hane-makikomi",          kanji: "跳巻込",   name_fr: "Enroulement bondissant",                   name_en: "Spring wraparound throw",                   group: 4, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/hane-makikomi/",  wikipedia_url: "https://en.wikipedia.org/wiki/Hane_makikomi",          image_url: "", youtube_id: "6CRBGLGz9j8" },
    Technique { slug: "sukui-nage",             name: "Sukui-nage",             kanji: "掬投",     name_fr: "Projection en cuillère",                   name_en: "Scooping throw",                            group: 4, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/sukui-nage/",               wikipedia_url: "https://en.wikipedia.org/wiki/Sukui_Nage",             image_url: "", youtube_id: "vU6aJ2kFxoI" },
    Technique { slug: "utsuri-goshi",           name: "Utsuri-goshi",           kanji: "移腰",     name_fr: "Hanche transférée",                        name_en: "Hip shift",                                 group: 4, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/utsuri-goshi/",          wikipedia_url: "https://en.wikipedia.org/wiki/Utsuri_goshi",           image_url: "", youtube_id: "4pQd_bEnlf0" },
    Technique { slug: "o-guruma",               name: "O-guruma",               kanji: "大車",     name_fr: "Grande roue",                              name_en: "Major wheel",                               group: 4, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/o-guruma/",               wikipedia_url: "https://en.wikipedia.org/wiki/%C5%8C_guruma",          image_url: "", youtube_id: "SnZciTAY9vc" },
    Technique { slug: "soto-makikomi",          name: "Soto-makikomi",          kanji: "外巻込",   name_fr: "Enroulement extérieur",                    name_en: "Outer wraparound throw",                    group: 4, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/soto-makikomi/",  wikipedia_url: "https://fr.wikipedia.org/wiki/Soto-Maki-Komi",         image_url: "", youtube_id: "bWG9O1BVKtQ" },
    Technique { slug: "uki-otoshi",             name: "Uki-otoshi",             kanji: "浮落",     name_fr: "Renversement flottant",                    name_en: "Floating drop",                             group: 4, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/uki-otoshi/",               wikipedia_url: "https://en.wikipedia.org/wiki/Uki_otoshi",             image_url: "", youtube_id: "6H5tmncOY4Q" },

    // ----- Dai Gokyō (5th group) -----
    Technique { slug: "o-soto-guruma",          name: "O-soto-guruma",          kanji: "大外車",   name_fr: "Grande roue extérieure",                   name_en: "Major outer wheel",                         group: 5, category: "ashi-waza",  judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/ashi-waza/o-soto-guruma/",          wikipedia_url: "https://fr.wikipedia.org/wiki/Gokyo_(judo)",           image_url: "", youtube_id: "92KbCm6pQeI" },
    Technique { slug: "uki-waza",               name: "Uki-waza",               kanji: "浮技",     name_fr: "Technique flottante",                      name_en: "Floating technique",                        group: 5, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/uki-waza/",       wikipedia_url: "https://en.wikipedia.org/wiki/Uki_waza",               image_url: "", youtube_id: "weVOpJ63gII" },
    Technique { slug: "yoko-wakare",            name: "Yoko-wakare",            kanji: "横分",     name_fr: "Séparation latérale",                      name_en: "Side separation",                           group: 5, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/yoko-wakare/",    wikipedia_url: "https://en.wikipedia.org/wiki/Yoko_wakare",            image_url: "", youtube_id: "bp1tscHlePI" },
    Technique { slug: "yoko-guruma",            name: "Yoko-guruma",            kanji: "横車",     name_fr: "Roue de côté",                             name_en: "Side wheel",                                group: 5, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/yoko-guruma/",    wikipedia_url: "https://en.wikipedia.org/wiki/Yoko_guruma",            image_url: "", youtube_id: "MehP6I5cY2c" },
    Technique { slug: "ushiro-goshi",           name: "Ushiro-goshi",           kanji: "後腰",     name_fr: "Hanche par derrière",                      name_en: "Rear hip throw",                            group: 5, category: "koshi-waza", judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/koshi-waza/ushiro-goshi/",          wikipedia_url: "https://en.wikipedia.org/wiki/Ushiro_goshi",           image_url: "", youtube_id: "ORIYstuxYT8" },
    Technique { slug: "ura-nage",               name: "Ura-nage",               kanji: "裏投",     name_fr: "Projection en arrière",                    name_en: "Back throw",                                group: 5, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/ma-sutemi-waza/ura-nage/",         wikipedia_url: "https://fr.wikipedia.org/wiki/Ura-nage",               image_url: "", youtube_id: "Fgi9b8DJ5sQ" },
    Technique { slug: "sumi-otoshi",            name: "Sumi-otoshi",            kanji: "隅落",     name_fr: "Renversement de l'angle",                  name_en: "Corner drop",                               group: 5, category: "te-waza",    judo_how_url: "https://judo.how/en/nage-waza/tachi-waza/te-waza/sumi-otoshi/",              wikipedia_url: "https://en.wikipedia.org/wiki/Sumi_otoshi",            image_url: "", youtube_id: "lLU9wv52ni0" },
    Technique { slug: "yoko-gake",              name: "Yoko-gake",              kanji: "横掛",     name_fr: "Accrochage de côté",                       name_en: "Side hook",                                 group: 5, category: "sutemi-waza",judo_how_url: "https://judo.how/en/nage-waza/sutemi-waza/yoko-sutemi-waza/yoko-gake/",      wikipedia_url: "https://en.wikipedia.org/wiki/Yoko_gake",              image_url: "", youtube_id: "" },
];

pub fn find(slug: &str) -> Option<&'static Technique> {
    TECHNIQUES.iter().find(|t| t.slug == slug)
}
